"""empty message

Revision ID: 1a50fa93b6a2
Revises: 
Create Date: 2023-12-01 13:10:46.130248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a50fa93b6a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('province', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=6), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(), nullable=True),
    sa.Column('l_initial', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_body', sa.String(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchaseorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('lname', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('cc_type', sa.String(), nullable=False),
    sa.Column('cc_last_4_digits', sa.String(), nullable=False),
    sa.Column('date_created', sa.String(), nullable=False),
    sa.Column('latest_update', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('image_file', sa.String(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('trim', sa.String(), nullable=False),
    sa.Column('colour', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('kilometres', sa.Integer(), nullable=False),
    sa.Column('max_range', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_file', sa.String(), nullable=False),
    sa.Column('date_added', sa.String(), nullable=False),
    sa.Column('is_for_sale', sa.Boolean(), nullable=False),
    sa.Column('is_trade_in', sa.Boolean(), nullable=False),
    sa.Column('history', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchaseorders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('quote', sa.Float(), nullable=False),
    sa.Column('accidents', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('date_updated', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitevents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipaddress', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('eventtype', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitevents')
    op.drop_table('trade_ins')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('purchaseorders')
    op.drop_table('ratings')
    op.drop_table('addresses')
    # ### end Alembic commands ###
