"""empty message

Revision ID: 9109fb928dfc
Revises: 92efe604f36c
Create Date: 2023-11-17 16:49:31.506901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9109fb928dfc'
down_revision = '92efe604f36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitevents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipaddress', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('eventtype', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitevents')
    # ### end Alembic commands ###
