"""empty message

Revision ID: 92efe604f36c
Revises: 2df019cd2498
Create Date: 2023-11-17 16:41:44.245057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92efe604f36c'
down_revision = '2df019cd2498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchaseorder_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['purchaseorders.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id', 'vehicle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchaseorder_vehicles')
    # ### end Alembic commands ###
